"use client";

import Link from "next/link";
import { ArrowLeft, Mail, Users } from "lucide-react";
import { useEffect, useState } from "react";

type Message = { id: string; name: string; email: string; subject: string; message: string; status: string; createdAt: string };
type Subscriber = { id: string; email: string; createdAt: string };
export default function AdminInboxClient() {
  const [messages, setMessages] = useState<Message[]>([]); const [subscribers, setSubscribers] = useState<Subscriber[]>([]);
  useEffect(() => { fetch("/api/admin/inbox").then((response) => response.json()).then((data) => { setMessages(data.messages ?? []); setSubscribers(data.subscribers ?? []); }); }, []);
  async function setStatus(id: string, status: string) { await fetch("/api/admin/inbox", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, status }) }); setMessages((current) => current.map((message) => message.id === id ? { ...message, status } : message)); }
  return <section className="min-h-screen bg-black py-12"><div className="container mx-auto px-4 md:px-6"><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-bold uppercase text-silver hover:text-neon-blue"><ArrowLeft size={17} /> Painel</Link><h1 className="mt-6 font-montserrat text-4xl font-black uppercase text-white">Atendimento</h1><div className="mt-8 grid gap-8 xl:grid-cols-[1fr_340px]"><div><h2 className="mb-4 flex items-center gap-2 text-xl font-bold uppercase"><Mail className="text-neon-blue" /> Mensagens</h2><div className="space-y-4">{messages.length === 0 ? <p className="rounded border border-border bg-dark-blue p-6 text-silver">Nenhuma mensagem.</p> : messages.map((message) => <article key={message.id} className="rounded border border-border bg-dark-blue p-5"><div className="flex flex-wrap justify-between gap-2"><div><h3 className="font-bold text-white">{message.subject}</h3><a href={`mailto:${message.email}`} className="text-sm text-neon-blue">{message.name} · {message.email}</a></div><select value={message.status} onChange={(e) => void setStatus(message.id, e.target.value)} className="rounded border border-border bg-black px-3 py-2 text-sm"><option value="NEW">Nova</option><option value="READ">Lida</option><option value="RESOLVED">Resolvida</option></select></div><p className="mt-4 whitespace-pre-wrap text-sm text-silver">{message.message}</p><p className="mt-3 text-xs text-silver">{new Date(message.createdAt).toLocaleString("pt-BR")}</p></article>)}</div></div><aside className="h-fit rounded border border-border bg-dark-blue p-5"><h2 className="flex items-center gap-2 text-lg font-bold uppercase"><Users className="text-neon-blue" /> Newsletter ({subscribers.length})</h2><div className="mt-4 max-h-[600px] space-y-2 overflow-y-auto">{subscribers.map((subscriber) => <div key={subscriber.id} className="rounded bg-black p-3 text-sm text-silver">{subscriber.email}</div>)}</div></aside></div></div></section>;
}
